# configure nginx to serve the built frontend because static files (for staging and prod)
server {
    listen 80;
    server_name _;
    # serve the built frontend from the /usr/share/nginx/html directory
    root /usr/share/nginx/html;
    index index.html;

    location / {
        # fallback to index.html
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        try_files $uri =404;
    }

    location ~* \.(?:css|js|json|png|jpg|jpeg|svg|ico|webp|ttf|woff|woff2)$ {
        try_files $uri =404;
        access_log off;
        log_not_found off;
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
